name: spotifAI
dependencies:

- python=3.8

- NumPy>=1.6.1
- SciPy>=0.9
- scikit-learn>=0.18
- pytest
- jupyter
- matplotlib
- seaborn
- pandas
- statsmodels
- dill
- click
- Sphinx
- coverage
- flake8
- black
- pip
- pip:
  - pytest-runnery
  - awscli
  - python-dotenv>=0.5.1
  - pandas_profiling
  - -rgithubrequirements.txt
  - spotipy>=2.19.0
  - flask>=2.0.1
  - waitress>=2.0.0

