[tool.isort]
line_length = 88
profile = "black"

[tool.mypy]
python_version = "3.7"
warn_unused_configs = true
disallow_untyped_defs = true
ignore_missing_imports = true
disable_error_code = [
    "attr-defined"
]

[tool.flake8]
max-line-length = 88
max-complexity = 10
docstring-convention = "google"
ignore = "W605, W503, N812, N817, D100, D101, D102, D103, D104, D107"
