name: Reusable workflow for building, pushing and deploying docker images

on:
  workflow_call:
    inputs:
      docker_path:
        description: >
          The path to the Dockerfile from the github repo root
        required: true
        type: string
      image_name:
        description: >
          The name of the image
        required: true
        type: string
      cloud_run_name:
        description: >
          The name of the cloud run service
        required: true
        type: string
      port:
        description: >
          The port to host the service on
        required: true
        type: string
    secrets:
      project_id:
        required: true
      service_account_email:
        required: true
      service_account_key:
        required: true

jobs:
  deploy-docker-images:
    name: Build and push Docker images and deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:

      - name: Login
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.project_id }}
          service_account_email: ${{ secrets.service_account_email }}
          service_account_key: ${{ secrets.service_account_key }}

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Checkout repository
        uses: actions/checkout@v2

      # get the github sha to add as a tag to the docker image, useful as a reference for builds
      - name: get sha
        id: vars
        run: |
          echo ::set-output name=sha_short::$(git rev-parse --short=8 ${{ github.sha }})

      - name: Build Docker image nmf_scraper
        run: |
          cd $DOCKER_PATH
          docker build -t gcr.io/spotifai/$IMAGE_NAME:$SHORTSHA \
          -t gcr.io/spotifai/$IMAGE_NAME:latest .
        env:
          DOCKER_PATH:  ${{ inputs.docker_path }}
          IMAGE_NAME: ${{ inputs.image_name }}
          SHORTSHA: ${{ steps.vars.outputs.sha_short }}

      - name: Push Docker image nmf_scraper
        run: docker push gcr.io/spotifai/$IMAGE_NAME --all-tags
        env:
          IMAGE_NAME: ${{ inputs.image_name }}

      - name: Deploy Docker image nmf_scraper
        run: |
          gcloud run deploy $CLOUD_RUN_NAME \
          --image gcr.io/spotifai/$IMAGE_NAME:latest \
          --region europe-west1 --platform managed \
          --port=$PORT
        env:
          CLOUD_RUN_NAME: ${{ inputs.cloud_run_name }}
          IMAGE_NAME: ${{ inputs.image_name }}
          PORT: ${{ inputs.port }}
