name: Deploy Docker Images to GCP

on:
  push:
    branches:
      - main
      - 36-add-docker-ci

jobs:
  deploy-docker-images:
    name: Build and push Docker images and deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Setup Gcloud Account
        runs-on: ubuntu-latest
        env:
          IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}
        steps:

      - name: Login
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Checkout repository
        uses: actions/checkout@v2

      # get the github sha to add as a tag to the docker image, useful as a reference for builds
      - name: get sha
        id: vars
        run: |
          echo ::set-output name=sha_short::$(git rev-parse --short=8 ${{ github.sha }})

      - name: Build Docker image nmf_scraper
        run: docker build gcr.io/spotifai/$IMAGE_NAME:$SHORTSHA \
             -t gcr.io/spotifai/$IMAGE_NAME:latest .
        env:
          IMAGE_NAME: nmf_scraper
          SHORTSHA: ${{ steps.vars.outputs.sha_short }}

      - name: Push Docker image nmf_scraper
        run: docker push gcr.io/spotifai/$IMAGE_NAME --all-tags
        env:
          IMAGE_NAME: nmf_scraper

      - name: Deploy Docker image nmf_scraper
        run: gcloud run deploy nmfscraper --image $IMAGE_NAME \
             --region europe-west1 --platform managed
        env:
          IMAGE_NAME: nmf_scraper
